<a href="https://colab.research.google.com/github/paulorobertolds/Hello-world/blob/main/Dados_Financeiros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/Colab Notebooks/Bootcamp/Dados

/content/drive/MyDrive/Colab Notebooks/Bootcamp/Dados

In [11]:
import pandas as pd
%ls

 Advertising.csv
 AutoML.pkl
'Blueprints for Text Analytics Using Python.pdf'
'Cod Siafi2003.csv'
'Cod Siafi2004.csv'
 corruptiondata_aer.csv
 datasetLischtig.csv
 datasetPoliticalResourceSmall-better.csv
 Despesa2004.csv
'Estatistica Aplicada e Probabilidade para Engenheiros.pdf'
 fig_selecao_features.png
 Finbra2003v0809.mdb
 Finbra2004v0809b.mdb
'Getting Started with Google BERT - Build and train state-of-the-art natural language processing models using BERT.pdf'
 iris_dataset.csv
 livros.parquet
 Passivo2003.csv
 Passivo2004.csv
 Publicidade.csv
'README-Finan and Ferraz (2011).pdf'
 RecDesp2003.csv
 Receita2004.csv
'The Elements of Data Analytic Style.pdf'

In [15]:
receita2004=pd.read_csv('Receita2004.csv')
receita2004.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (89,90,92,137,140) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   CD_UF  CD_MUN  ... Dedução FUNDEF ICMS Dedução FUNDEF IPI Exp
0     11       1  ...          682,310.67                   0.00
1     11       2  ...        2,826,850.37                   0.00
2     11       3  ...          216,543.65                   0.00
3     11       4  ...        2,466,125.00                   0.00
4     11       5  ...                0.00                   0.00

[5 rows x 148 columns]

ModuleNotFoundError: ignored